### ISSUE TITLE
RTSP preview

### ISSUE THREAD

**Issue by pergolafabio** [divusgmbh/linhome-Android#1]
Hi team or @mediamagic-dev 

In the "old" videophone app, we had an option define an RTSP preview, for early media or when in call

Is it maybe possible to have this option too in this new app? Could ve verry usefull with a door intercom that doesnt send video, so we can add it manually by injecting rtsp

Thnx in advance

**Comment by s-mittelberger** [comment]
Hi @pergolafabio,

thanks for your inquiry.

The target use case of Videophone Mobile App is to be able to receive calls from an door intercom when abroad, via our cloud service, and to be able to "call" into you door intercom to access the spy cam from abroad. The App is a pure SIP client and supports only SIP based media streams (audio/video). The reason for this is that for most users it is not easily possible to setup other streaming protocols like RTSP as they would require a special port forwarding rule or an relay somewhere on the Internet.

BR,
Simon

**Comment by pergolafabio** [comment]
Ahh, that's too bad :-(

Sending video in 183 session (early media) is no issue...

But the problem with every PBX also your cloud, is when you start calling to groups (multiple endpoint's) then there is no video before pick-up, only afterwards...
That beats the purpose of a door intercom app, you don't see who is calling :-)

**Comment by s-mittelberger** [comment]
> But the problem with every PBX also your cloud, is when you start calling to groups (multiple endpoint's) then there is no video before pick-up, only afterwards...
That beats the purpose of a door intercom app, you don't see who is calling :-)

I can assure you that when you use a DIVUS intercom together with the DIVUS cloud service and the DIVUS Videophone Mobile, the video stream is in fact displayed on multiple devices before the call is picked up. After call pick up obviously only one callee receives it and the others are hung up.

I am closing the issue, feel free to reopen if you have further questions.

**Comment by pergolafabio** [comment]
ok, then i need to test again
1 last question then

You are saying that early media is possible on all registered endpoints, then who is serving this?
Is it the DVIUS intercom? or is it your cloud that is abe to send the video in 183 session to groups?

i believe the stream/channels must be splitted by the PBX and not the intercpm, right?
SO if i hookup another non-divus intercom to the cloud, one that is able to send video in 183 session, i should see also the video stream when i call to a group ?

**Comment by s-mittelberger** [comment]
> You are saying that early media is possible on all registered endpoints, then who is serving this?
Is it the DVIUS intercom? or is it your cloud that is abe to send the video in 183 session to groups?

The DIVUS intercom

> i believe the stream/channels must be splitted by the PBX and not the intercpm, right?
SO if i hookup another non-divus intercom to the cloud, one that is able to send video in 183 session, i should see also the video stream when i call to a group?

The DIVUS cloud does not use groups currently. I am sorry, but i can not know how your non-divus intercom works.

**Comment by pergolafabio** [comment]
Flexisip supports groups, i do it too with Linhome

I just connect my intercom to asterisk
In asterisk i setup an outbund trunk , created an divus account for the trunk

Then in dialplan, i call a group where i add 2 other divus cloud users , using the outbound trunk i setup earlier
